# Generated by Django 4.1 on 2023-07-26 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_tag_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["is_done", "-create_at"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
