# Generated by Django 4.1 on 2023-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
